foundation = lib{dagforge-foundation}

./: lib{dagforge} lib{dagforge-jsonata}

intf_libs = -lboost_url

./: lib{dagforge-foundation}: libul{dagforge-foundation}: \
  cxx{dagforge/util/id}                                        \
  mxx{modules/base modules/core modules/util modules/domain modules/io \
      modules/config modules/http modules/sandbox modules/workflow \
      modules/executors                                            \
      modules/dagforge}

lib{dagforge-foundation}:
{
  cxx.export.poptions = "-I$src_root/include" \
                        "-I$src_root/third_party/unordered_dense/include"
  cxx.export.libs = $intf_libs
}

mxx{modules/*}:
{
  install = include/dagforge/
  install.subdirs = true
}

lib{dagforge-jsonata}:                                           \
  cxx{dagforge/jsonata/detail/model                              \
      dagforge/jsonata/detail/json_adapter                       \
      dagforge/jsonata/detail/signature                          \
      dagforge/jsonata/detail/unicode                            \
      dagforge/jsonata/detail/regex_adapter                      \
      dagforge/jsonata/detail/datetime                           \
      dagforge/jsonata/detail/lexer                              \
      dagforge/jsonata/detail/parser                             \
      dagforge/jsonata/detail/path_ast                           \
      dagforge/jsonata/detail/evaluator                          \
      dagforge/jsonata/detail/builtins                           \
      dagforge/jsonata/program}                                  \
  $foundation
{
  cxx.libs = -lpcre2-8
}

lib{dagforge}:                                                   \
  cxx{dagforge/core/shard                                         \
      dagforge/core/runtime                                       \
      dagforge/workflow/storage/artifact_store                    \
      dagforge/workflow/storage/checkpoint_store                  \
      dagforge/workflow/storage/detail/checkpoint_validator      \
      dagforge/workflow/storage/detail/durable_file              \
      dagforge/workflow/storage/detail/json_file_catalog         \
      dagforge/workflow/storage/detail/storage_directory_lock    \
      dagforge/workflow/storage/detail/storage_codec              \
      dagforge/workflow/detail/sha256                            \
      dagforge/workflow/detail/repair_planner                     \
      dagforge/workflow/detail/retry_policy                       \
      dagforge/workflow/detail/state_machine                      \
      dagforge/workflow/model/workflow_value                     \
      dagforge/workflow/storage/evidence_ledger                   \
      dagforge/workflow/runtime/execution_failure                 \
      dagforge/workflow/runtime/executor_registry                 \
      dagforge/workflow/planning/plan_compiler                    \
      dagforge/workflow/planning/workflow_capability_catalog      \
      dagforge/workflow/storage/plan_store                        \
      dagforge/workflow/planning/plan_validator                   \
      dagforge/workflow/runtime/run_value_store                   \
      dagforge/workflow/runtime/workflow_runtime                  \
      dagforge/workflow/runtime/workflow_runtime_bootstrap        \
      dagforge/workflow/planning/workflow_control_plane           \
      dagforge/workflow/planning/workflow_plan_loader            \
      dagforge/io/context                                         \
      dagforge/io/timing_wheel                                    \
      dagforge/app/metrics_exporter                               \
      dagforge/sandbox/detail/command_policy                      \
      dagforge/sandbox/detail/policy_command_runner               \
      dagforge/sandbox/minijail_command_runner                    \
      dagforge/executors/command/executor                         \
      dagforge/executors/http/egress_policy                       \
      dagforge/executors/http/executor                            \
      dagforge/executors/transform/detail/evaluation              \
      dagforge/executors/transform/executor                       \
      dagforge/app/application                                    \
      dagforge/app/api/api_server                                 \
      dagforge/app/api/detail/http_metrics_registry               \
      dagforge/app/api/detail/routes/system                       \
      dagforge/app/api/detail/routes/workflow_http_adapter        \
      dagforge/app/api/detail/routes/workflows                    \
      dagforge/http/detail/beast_bridge                           \
      dagforge/http/router                                        \
      dagforge/http/http_server                                   \
      dagforge/http/http_client                                   \
      dagforge/config/system_config_loader                        \
      dagforge/util/daemon                                        \
      dagforge/util/log}                                          \
  $foundation                                                     \
  lib{dagforge-jsonata}                                           \
  ../third_party/prometheus-cpp-core/cxx{check_names             \
      counter                                                     \
      detail_builder                                              \
      detail_ckms_quantiles                                       \
      detail_time_window_quantiles                                \
      detail_utils                                                \
      family                                                      \
      gauge                                                       \
      histogram                                                   \
      info                                                        \
      registry                                                    \
      serializer                                                  \
      summary                                                     \
      text_serializer}
{
  cxx.poptions += "-DBOOST_ASIO_HAS_IO_URING=0" \
                  "-DDAGFORGE_USE_MIMALLOC=0"
  c.libs = -lm -ldl
  cxx.libs = -lboost_url -lboost_charconv -lboost_process -lssl -lcrypto -pthread -lm -ldl
  cxx.export.libs = -lboost_url -lboost_charconv -lboost_process -lssl -lcrypto -pthread -lm -ldl
}

mxx{modules/dagforge}@modules/: cxx.module_name = dagforge.foundation
mxx{modules/base}@modules/: cxx.module_name = dagforge.base
mxx{modules/core}@modules/: cxx.module_name = dagforge.core
mxx{modules/util}@modules/: cxx.module_name = dagforge.util
mxx{modules/domain}@modules/: cxx.module_name = dagforge.domain
mxx{modules/io}@modules/: cxx.module_name = dagforge.io
mxx{modules/config}@modules/: cxx.module_name = dagforge.config
mxx{modules/http}@modules/: cxx.module_name = dagforge.http
mxx{modules/sandbox}@modules/: cxx.module_name = dagforge.sandbox
mxx{modules/executors}@modules/: cxx.module_name = dagforge.executors
mxx{modules/workflow}@modules/: cxx.module_name = dagforge.workflow
