import foundation = lib{dagforge-foundation}

./: lib{dagforge}

intf_libs = -lboost_url

./: lib{dagforge-foundation}: libul{dagforge-foundation}: \
  mxx{modules/base modules/core modules/util modules/domain modules/io \
      modules/config modules/http modules/executor modules/workflow \
      modules/dagforge}

lib{dagforge-foundation}:
{
  cxx.export.poptions = "-I$src_root/include" \
                        "-I$src_root/third_party/unordered_dense/include" \
                        "-DDAGFORGE_USE_STDLIB_MODULES=0"
  cxx.export.libs = $intf_libs
}

mxx{modules/*}:
{
  install = include/dagforge/
  install.subdirs = true
}

lib{dagforge}:                                                   \
  cxx{dagforge/core/shard                                         \
      dagforge/core/runtime                                       \
      dagforge/workflow/admission_policy                          \
      dagforge/workflow/artifact_store                            \
      dagforge/workflow/checkpoint_store                          \
      dagforge/workflow/detail/storage_codec                      \
      dagforge/workflow/evidence_ledger                           \
      dagforge/workflow/executor_registry                         \
      dagforge/workflow/plan_compiler                             \
      dagforge/workflow/run_value_store                           \
      dagforge/workflow/workflow_runtime                          \
      dagforge/workflow/workflow_control_plane                    \
      dagforge/workflow/workflow_plan_loader                     \
      dagforge/io/context                                         \
      dagforge/io/timing_wheel                                    \
      dagforge/app/metrics_exporter                               \
      dagforge/executor/command_executor                          \
      dagforge/workflow/executors/command_adapter                 \
      dagforge/workflow/executors/http_adapter                    \
      dagforge/app/application                                    \
      dagforge/app/api/api_server                                 \
      dagforge/app/api/detail/http_metrics_registry               \
      dagforge/app/api/detail/routes/system                       \
      dagforge/app/api/detail/routes/workflows                    \
      dagforge/http/http_parser                                   \
      dagforge/http/router                                        \
      dagforge/http/http_server                                   \
      dagforge/http/http_client                                   \
      dagforge/config/system_config_loader                        \
      dagforge/util/daemon                                        \
      dagforge/util/log}                                          \
  $foundation                                                     \
  ../third_party/prometheus-cpp-core/cxx{check_names             \
      counter                                                     \
      detail_builder                                              \
      detail_ckms_quantiles                                       \
      detail_time_window_quantiles                                \
      detail_utils                                                \
      family                                                      \
      gauge                                                       \
      histogram                                                   \
      info                                                        \
      registry                                                    \
      serializer                                                  \
      summary                                                     \
      text_serializer}
{
  cxx.poptions += "-DBOOST_ASIO_HAS_IO_URING=0" \
                  "-DDAGFORGE_USE_MIMALLOC=0"
  c.libs = -lm -ldl
  cxx.libs = -lboost_url -lboost_charconv -lboost_process -lssl -lcrypto -pthread -lm -ldl
  cxx.export.libs = -lboost_url -lboost_charconv -lboost_process -lssl -lcrypto -pthread -lm -ldl
}

mxx{modules/dagforge}@modules/: cxx.module_name = dagforge.foundation
mxx{modules/base}@modules/: cxx.module_name = dagforge.base
mxx{modules/core}@modules/: cxx.module_name = dagforge.core
mxx{modules/util}@modules/: cxx.module_name = dagforge.util
mxx{modules/domain}@modules/: cxx.module_name = dagforge.domain
mxx{modules/io}@modules/: cxx.module_name = dagforge.io
mxx{modules/config}@modules/: cxx.module_name = dagforge.config
mxx{modules/http}@modules/: cxx.module_name = dagforge.http
mxx{modules/executor}@modules/: cxx.module_name = dagforge.executor
mxx{modules/workflow}@modules/: cxx.module_name = dagforge.workflow
